#!/bin/sh

if [ $# -ne 4 ];then
	echo "Usage : $0 PROCESS SEVERITY CELL_NAME EVENT_CLASS"
	exit 0
fi

PROCESS="$1"
SEVERITY="$2"
CELL_NAME="$3"
EVENT_CLASS="$4"
HOSTNAME=`hostname`


/usr/bin/msend.sh "$SEVERITY" "$CELL_NAME" "Process [$PROCESS] is down" "Process" "$EVENT_CLASS" "$HOSTNAME" "Process:$PROCESS" "Down" "monit"
